package router

import (
	"net/http"
	"vtmtea.com/f.cli/handler/book"

	// docs is generated by Swag CLI, you have to import it.
	"github.com/gin-contrib/pprof"
	"github.com/gin-gonic/gin"
	_ "vtmtea.com/f.cli/docs"
	"vtmtea.com/f.cli/handler/sd"
	"vtmtea.com/f.cli/router/middleware"

	"github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

// Load middlewares, routes, handlers
func Load(g *gin.Engine, mw ...gin.HandlerFunc) *gin.Engine {

	// Middlewares
	g.Use(gin.Recovery())
	g.Use(middleware.NoCache)
	g.Use(middleware.Options)
	g.Use(middleware.Secure)
	g.Use(mw...)

	g.NoRoute(func(c *gin.Context) {
		c.String(http.StatusNotFound, "Not found!")
	})

	// swagger api docs
	g.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// pprof router
	pprof.Register(g)

	v1 := g.Group("/v1")
	//更新单本小说
	v1.POST("/update/book", book.Update)
	//抓取小说列表
	v1.GET("/fetch/list", book.FetchList)

	svcd := g.Group("/sd")
	{
		svcd.GET("/health", sd.HealthCheck)
	}

	return g
}
